name: CVE Check
on:
  schedule:
    - cron:  '15 3 1 * *' # At 03:15 on day-of-month 1.
  workflow_dispatch:
jobs:
  build:
    env:
      CVE_SCORE: 9.2
      MAVEN_CLI_OPTS: "
        -B
        -f aws-sns-subscription-cleaner/pom.xml
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -Dlog4j2.formatMsgNoLookups=true
        -Dmaven.test.skip=true
        -Powasp-dependency-check
      "
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Check dependencies
      run: mvn $MAVEN_CLI_OPTS install

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cve-report
        path: aws-sns-subscription-cleaner/target/dependency-check-report.html
