name: Main
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:
jobs:
  build:
    env:
      MAVEN_CLI_OPTS: "
        -B
        -f aws-sns-subscription-cleaner/pom.xml
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -Dlog4j2.formatMsgNoLookups=true
      "
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Run tests
      run: mvn $MAVEN_CLI_OPTS package

    - uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: aws-sns-subscription-cleaner/target/site/jacoco

    - name: Read code coverage
      run: echo "coverage=$(cat aws-sns-subscription-cleaner/target/site/jacoco/index.html | grep -iPo 'Total.*?\K([0-9]{1,3})%')" >> $GITHUB_ENV

    - name: Generate coverage badge
      uses: ./.github/actions/generate-badge
      with:
        label: Coverage
        message: ${{ env.coverage }}
        color: green
        location: .github/badges/coverage.svg

    - name: Commit and push generated resources
      uses: ./.github/actions/commit
      with:
        username: Amazon GitHub Automation
        useremail: amazon-auto@users.noreply.github.com
        message: Add auto generated resources
